#!/usr/bin/env python3
"""Validate coverage and freshness of the authored Work Package B RH review.

Task: finite verification; assumptions: UNCONDITIONAL. Verdicts and reasons
are authored proof review, not generated by this checker. No independent
review, formal proof, or numerical certificate is asserted.
"""
import hashlib
import json
from pathlib import Path
import unittest

from check_pair_rh_audit import field, id_list, indexed_blocks, require, unique_object
from check_triple_dependencies import (
    closure, flat_section, scalar, subsection, validate as validate_graph,
)

ROOT = Path(__file__).resolve().parents[1]
RECORD = 'research/triple-rh-audit.json'
MAIN = 'proofs/triple_explicit_formula.tex'
LEDGER = 'research/theorem-ledger.yaml'
GRAPH = 'research/triple-dependency-graph.json'
GRAPH_REPORT = 'research/triple-dependency-graph.md'
PAIR = 'research/pair-rh-audit.json'
KINDS = {'nonmathematical', 'exposition', 'definition', 'statement', 'proof',
         'imported_input', 'parameter_specialization', 'conditional_interpretation',
         'verification_only'}
VERDICTS = {'justified', 'isolated_conditional_interpretation', 'unresolved'}


def read_file(path):
    return (ROOT/path).read_bytes()


def digest(raw):
    return hashlib.sha256(raw).hexdigest()


def load_json(path, read=read_file):
    return json.loads(read(path), object_pairs_hook=unique_object)


def assumptions(raw):
    """The reviewed ledger uses a bare UNCONDITIONAL followed by quoted support."""
    require(raw.startswith('[UNCONDITIONAL') and raw.endswith(']'),
            'unsupported assumption syntax')
    result = json.loads(raw.replace('[UNCONDITIONAL', '["UNCONDITIONAL"', 1))
    require(result[0] == 'UNCONDITIONAL' and
            all(isinstance(x, str) and x.startswith('SUPPORT(') and x.endswith(')')
                for x in result[1:]), 'unsupported claim assumptions')
    return result


def context(read=read_file):
    graph = load_json(GRAPH, read)
    validate_graph(graph, read(GRAPH_REPORT).decode(), read)
    pair = load_json(PAIR, read)
    text = read(LEDGER).decode()
    blocks = indexed_blocks(text)
    sources = set(indexed_blocks(text.split('\nclaims:\n', 1)[0]))
    triple = sorted(k for k in blocks if k.startswith('TRIPLE-'))
    deps, pending = {}, list(triple)
    while pending:
        key = pending.pop()
        require(key in blocks, 'unknown dependency')
        if key in deps:
            continue
        deps[key] = [] if key in sources else id_list(field(blocks[key], 'dependencies'))
        pending.extend(deps[key])
    # A virtual root permits checking the union, including the three older claims.
    seen, all_edges = closure('AUDIT-ROOT', dict(deps, **{'AUDIT-ROOT': triple}))
    seen.remove('AUDIT-ROOT')
    edges = [e for e in all_edges if e[0] != 'AUDIT-ROOT']
    snapshots = {}
    for key in sorted(seen-sources):
        block = blocks[key]
        snapshots[key] = dict(status=field(block, 'status'),
            assumptions=field(block, 'assumptions'), dependencies=deps[key],
            source=flat_section(subsection(block, 'source')),
            ledger_block_sha256=digest(block.encode()))
        for name in ('computation_used_in_proof', 'constants_effective',
                     'all_limit_interchanges_justified', 'dependency_graph_complete'):
            snapshots[key][name] = scalar(field(block, name))
    inherited = sorted(set(snapshots) & pair['claim_snapshot'].keys())
    return dict(root_claim=graph['root_claim'], triple_claim_ids=triple,
        claim_snapshot=snapshots, source_node_ids=sorted(seen & sources), edges=edges,
        inherited_claim_ids=inherited,
        inherited_passages={k: [f['path']+': '+p['id'] for f in pair['files']
            for p in f['passages'] if k in p['claim_ids']] for k in inherited},
        inherited_evidence=[e for e in pair['evidence'] if e['claim_id'] in snapshots])


def passage_assumptions(ids, snapshots, kind):
    if kind == 'nonmathematical': return []
    if kind == 'conditional_interpretation': return ['RH']
    values = {a for key in ids for a in assumptions(snapshots[key]['assumptions'])}
    return ['UNCONDITIONAL']+sorted(values-{'UNCONDITIONAL'})


def validate(record, read=read_file, require_clean=True):
    require(record['schema_version'] == 1, 'unknown audit schema')
    require(record['task'] == 'exposition_and_proof_review', 'wrong audit task')
    require(record['assumptions'] == ['UNCONDITIONAL'], 'wrong task assumptions')
    require(record['independent_review'] is False and
            record['analytic_proof_certificate'] is False, 'unsupported verification claim')
    expected = context(read)
    require(record['context'] == expected, 'changed claims, support, dependencies or inherited evidence')
    require(set(record['input_hashes']) == {LEDGER, GRAPH, GRAPH_REPORT, PAIR},
            'missing or extra bound input')
    for path, sha in record['input_hashes'].items():
        require(digest(read(path)) == sha, 'stale input: '+path)
    snapshots = expected['claim_snapshot']
    triples = set(expected['triple_claim_ids'])
    passages, paths, unresolved, covered = set(), set(), [], set()
    main_count = 0
    conditional_ids, parameter_ids = [], []
    evidence = {e['id'] for e in expected['inherited_evidence']} | {'sine-context'}
    require(record['supplemental_evidence']['sine-context']['path'] ==
            'research/literature-notes/triple-sine-comparison.md', 'missing benchmark source note')
    for f in record['files']:
        path = f['path']
        require(path not in paths and not Path(path).is_absolute() and
                '..' not in Path(path).parts, 'duplicate/invalid reviewed file')
        paths.add(path)
        raw = read(path); lines = raw.decode().splitlines()
        require(digest(raw) == f['sha256'], 'stale source: '+path)
        require(len(lines) == f['line_count'], 'stale line count')
        require(f['coverage'] in ('complete', 'selected_passages'), 'invalid coverage')
        if path == MAIN:
            require(f['coverage'] == 'complete', 'main coverage must be complete')
        previous = 0
        for p in f['passages']:
            require(p['id'] not in passages, 'duplicate passage')
            passages.add(p['id'])
            a, b = p['start_line'], p['end_line']
            require(type(a) is int and type(b) is int and previous < a <= b <= len(lines),
                    'overlap or invalid lines')
            if f['coverage'] == 'complete':
                require(a == previous+1, 'coverage gap')
            previous = b
            kind = p['kind']; ids = p['claim_ids']
            require(kind in KINDS and p['verdict'] in VERDICTS, 'unknown classification')
            require(len(ids) == len(set(ids)) and set(ids) <= snapshots.keys(), 'unknown/duplicate claim')
            require(bool(ids) == (kind != 'nonmathematical'), 'claim attribution')
            required = passage_assumptions(ids, snapshots, kind)
            if kind == 'verification_only' and p['synthetic_fixture']:
                required.append('SYNTHETIC_MODEL')
            require(p['assumptions'] == required, 'dropped/misclassified assumptions or support')
            require(p['claim_assumptions'] == {k: snapshots[k]['assumptions'] for k in ids},
                    'changed passage claim assumptions')
            require(p['reason'].strip() and len(p['reason']) >= 35, 'missing specific justification')
            require(len(p['evidence_ids']) == len(set(p['evidence_ids'])) and
                    set(p['evidence_ids']) <= evidence, 'unknown/duplicate evidence')
            if kind == 'conditional_interpretation':
                require('RH' in '\n'.join(lines[a-1:b]), 'unmarked conditional interpretation')
                require(p['verdict'] in ('isolated_conditional_interpretation', 'unresolved'),
                        'unisolated conditional interpretation')
                conditional_ids.append(p['id'])
            else:
                require(p['verdict'] != 'isolated_conditional_interpretation', 'conditional verdict mismatch')
            if kind == 'parameter_specialization': parameter_ids.append(p['id'])
            if p['verdict'] == 'unresolved': unresolved.append(p['id'])
            if path == MAIN:
                main_count += 1
                if kind not in ('nonmathematical', 'conditional_interpretation'):
                    covered.update(set(ids) & triples)
        require(f['passages'], 'empty reviewed file')
        if f['coverage'] == 'complete': require(previous == len(lines), 'unreviewed final lines')
    require(MAIN in paths and covered == triples, 'missing manuscript claim coverage')
    require(record['conditional_interpretation_ids'] == conditional_ids and conditional_ids,
            'conditional interpretation inventory')
    require(record['parameter_specialization_ids'] == parameter_ids and parameter_ids,
            'parameter specialization inventory')
    require(record['supplemental_evidence']['sine-context']['path'] in paths, 'unreviewed source note')
    for finding in record['findings']:
        require(finding['category'] in ('editorial', 'analytic', 'rh_contamination'), 'finding category')
        require(finding['status'] in ('resolved', 'unresolved'), 'finding status')
        require(finding['resolution'].strip(), 'finding resolution missing')
        if finding['status'] == 'unresolved': unresolved.append(finding['id'])
        elif finding['category'] == 'editorial':
            require(finding['after'] in read(finding['path']).decode(), 'correction missing')
            require(finding['before'] not in read(finding['path']).decode(), 'correction not applied')
    require(record['unresolved_ids'] == unresolved, 'unresolved inventory mismatch')
    if unresolved:
        require(record['outcome'] == 'unresolved_findings', 'clean outcome with unresolved findings')
    else:
        require(record['outcome'] == 'no_contamination_found_in_reviewed_scope', 'outcome mismatch')
    if require_clean: require(not unresolved, 'unresolved local passages or findings')
    return dict(main_passages=main_count, total_passages=len(passages), files=len(paths),
                claims=len(snapshots), unresolved=unresolved)


class TripleRHAuditChecks(unittest.TestCase):
    def test_authored_review_coverage_and_freshness(self):
        result = validate(load_json(RECORD))
        self.assertEqual(result['claims'], 34)
        self.assertGreater(result['main_passages'], 100)
        self.assertFalse(result['unresolved'])

    def test_reject_gaps_overlaps_and_missing_tail(self):
        for change in ('gap', 'overlap', 'tail'):
            r = load_json(RECORD); p = r['files'][0]['passages']
            if change == 'gap': p[1]['start_line'] += 1
            if change == 'overlap': p[1]['start_line'] -= 1
            if change == 'tail': p.pop()
            with self.assertRaises(ValueError): validate(r)

    def test_reject_stale_proof_ledger_graph_and_supplement(self):
        for path in (MAIN, LEDGER, GRAPH, 'research/triple-kernel.md'):
            def read(p): return read_file(p)+(b'\n' if p == path else b'')
            with self.assertRaises(ValueError): validate(load_json(RECORD), read)

    def test_reject_missing_claim_evidence_and_duplicate_passage(self):
        for change in ('claim', 'evidence', 'duplicate'):
            r = load_json(RECORD)
            if change == 'claim': del r['context']['claim_snapshot']['TRIPLE-MASTER-001']
            if change == 'evidence': r['context']['inherited_evidence'].pop()
            if change == 'duplicate': r['files'][0]['passages'][1]['id'] = r['files'][0]['passages'][0]['id']
            with self.assertRaises(ValueError): validate(r)

    def test_reject_lost_support_and_conditional_misclassification(self):
        r = load_json(RECORD)
        p = next(p for p in r['files'][0]['passages'] if len(p['assumptions']) > 1)
        p['assumptions'] = ['UNCONDITIONAL']
        with self.assertRaisesRegex(ValueError, 'assumptions or support'): validate(r)
        r = load_json(RECORD)
        p = next(p for p in r['files'][0]['passages'] if p['kind'] == 'conditional_interpretation')
        p['assumptions'] = ['UNCONDITIONAL']
        with self.assertRaises(ValueError): validate(r)

    def test_unresolved_records_are_preserved_but_cannot_pass_clean_check(self):
        r = load_json(RECORD); p = r['files'][0]['passages'][1]
        p['verdict'] = 'unresolved'; r['unresolved_ids'] = [p['id']]
        with self.assertRaisesRegex(ValueError, 'clean outcome'): validate(r, require_clean=False)
        r['outcome'] = 'unresolved_findings'
        self.assertEqual(validate(r, require_clean=False)['unresolved'], [p['id']])
        with self.assertRaisesRegex(ValueError, 'unresolved local'): validate(r)

    def test_reject_false_coverage_unknown_references_and_duplicate_json(self):
        r = load_json(RECORD)
        r['context']['inherited_claim_ids'].append('TRIPLE-MASTER-001')
        with self.assertRaises(ValueError): validate(r)
        r = load_json(RECORD); r['files'][0]['passages'][1]['evidence_ids'] = ['missing']
        with self.assertRaises(ValueError): validate(r)
        with self.assertRaises(ValueError): json.loads('{"x":1,"x":2}', object_pairs_hook=unique_object)


if __name__ == '__main__':
    unittest.main(verbosity=2)
