#!/usr/bin/env python3
"""Offline reproduction of the weighted triple theorem (installed Python 3.12).

Task: verification/exposition. UNCONDITIONAL algebra with recorded support.
No analytic proof certificate or independent mathematical verification.
"""
import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import platform
import re
import shutil
import sys

from reproduce_pair import execute, input_hashes, prepare_output, sha256, tex_diagnostics
from triple_normalization import CLAIM, SUPPORT, generate, json_text, markdown
from check_pair_rh_audit import validate as validate_pair
from check_triple_dependencies import validate as validate_graph
from check_triple_rh_audit import validate as validate_audit, unique_object

ROOT = Path(__file__).resolve().parents[1]


def source_state(root, out, manifest, suffix=''):
    git = shutil.which('git')
    if not git:
        raise RuntimeError('missing prerequisite: git')
    commit = execute(manifest, out, 'source-commit'+suffix, [git, 'rev-parse', 'HEAD'], root).strip()
    status = execute(manifest, out, 'source-status'+suffix,
                     [git, 'status', '--porcelain=v1', '--untracked-files=all'], root)
    return {'commit': commit, 'dirty': bool(status.strip()), 'git_status': status.splitlines()}


def collect_environment(root, out, manifest, checks_only, require_clean):
    if sys.version_info[:2] != (3, 12):
        raise RuntimeError('Python 3.12 is required; use an installed Python 3.12 interpreter')
    state = source_state(root, out, manifest)
    manifest['source'].update(state)
    if require_clean and state['dirty']:
        raise RuntimeError('--require-clean rejects a dirty source tree')
    git = shutil.which('git')
    manifest['environment']['git'] = execute(manifest, out, 'git-version', [git, '--version'], root).strip()
    tools = {}
    if not checks_only:
        executable = shutil.which('pdflatex')
        if not executable:
            raise RuntimeError('missing prerequisite: pdflatex; install TeX or use --checks-only')
        tools['pdflatex'] = executable
        version = execute(manifest, out, 'pdflatex-version', [executable, '--version'], root)
        manifest['environment']['pdflatex'] = {'executable': executable, 'version': version.strip()}
    return tools


def validate_records(root):
    read = lambda path: (root/path).read_bytes()
    load = lambda path: json.loads(read(path), object_pairs_hook=unique_object)
    # Each audit checks its own bound sources; none is regenerated by this run.
    pair = load('research/pair-rh-audit.json')
    validate_pair(pair, read)
    graph = validate_graph(load('research/triple-dependency-graph.json'),
                           read('research/triple-dependency-graph.md').decode(), read)
    audit = validate_audit(load('research/triple-rh-audit.json'), read)
    return {'status': 'pass', 'pair_claims': len(pair['claim_snapshot']),
            'triple_dependency_graph': graph, 'triple_audit': audit}


def check_test_log(output, minimum):
    match = re.search(r'^Ran (\d+) tests? in ', output, re.M)
    if not match or int(match[1]) < minimum or not re.search(r'^OK\s*$', output, re.M):
        raise RuntimeError(f'test discovery must report at least {minimum} tests and an unqualified OK')
    return int(match[1])


def run_checks(root, out, manifest):
    for suite, minimum in (('pair', 70), ('triple', 96)):
        print(f'Running {suite} regression and audit checks...', flush=True)
        manifest['tests'][suite] = {'status': 'running'}
        try:
            output = execute(manifest, out, suite+'-checks',
                [sys.executable, '-B', '-m', 'unittest', 'discover', '-s', 'scripts',
                 '-p', f'check_{suite}_*.py', '-v'], root)
            count = check_test_log(output, minimum)
            manifest['tests'][suite] = {'status': 'pass', 'run': count,
                                       'failures': 0, 'errors': 0, 'skipped': 0}
        except RuntimeError as error:
            manifest['tests'][suite] = {'status': 'fail', 'error': str(error)}
            raise


def build_pdf(root, out, manifest, tools):
    print('Building the triple manuscript...', flush=True)
    manifest['pdf']['status'] = 'running'
    try:
        build = out/'build/proofs'
        build.mkdir(parents=True)
        shutil.copy2(root/'proofs/triple_explicit_formula.tex', build)
        command = [tools['pdflatex'], '-no-shell-escape', '-interaction=nonstopmode',
                   '-halt-on-error', '-file-line-error', 'triple_explicit_formula.tex']
        for i in range(1, 4):
            execute(manifest, out, f'tex-{i}', command, build)
        log = (build/'triple_explicit_formula.log').read_text(errors='replace')
        failures, warnings = tex_diagnostics(log)
        manifest['pdf'].update(failures=failures, warnings=warnings)
        if failures:
            raise RuntimeError('unresolved TeX references/citations or rerun request; see final TeX log')
        pdf = build/'triple_explicit_formula.pdf'
        if not pdf.is_file() or not pdf.read_bytes().startswith(b'%PDF-'):
            raise RuntimeError('TeX did not produce a PDF')
        shutil.copy2(pdf, out/'triple_explicit_formula.pdf')
        pages = re.search(r'Output written on .*?\((\d+) pages?', log, re.S)
        manifest['pdf'].update(status='pass', pages=int(pages[1]) if pages else None)
    except (OSError, RuntimeError) as error:
        manifest['pdf'].update(status='fail', error=str(error))
        raise


def reproduce(root, out, checks_only=False, require_clean=False):
    manifest = {
        'schema_version': 1, 'task': 'verification_and_exposition',
        'assumptions': ['UNCONDITIONAL', SUPPORT], 'analytic_proof_certificate': False,
        'independent_mathematical_verification': False,
        'claim_ids': [CLAIM], 'claim_status': 'proved-draft',
        'mode': 'checks-only' if checks_only else 'full', 'status': 'running',
        'require_clean': require_clean, 'started_utc': datetime.now(timezone.utc).isoformat(),
        'source': {'root': str(root), 'commit': None, 'dirty': None},
        'environment': {'python': sys.version, 'python_executable': sys.executable,
                        'platform': platform.platform(), 'provisioned_by_harness': False},
        'inputs': {}, 'stages': [], 'tests': {k: {'status': 'not_run'} for k in ('pair', 'triple')},
        'records': {'status': 'not_run'},
        'pdf': {'status': 'skipped' if checks_only else 'not_run'},
        'external_computational_proofs_replayed': False,
    }
    try:
        manifest['inputs'] = input_hashes(root)
        tools = collect_environment(root, out, manifest, checks_only, require_clean)
        manifest['records']['status'] = 'running'
        try:
            manifest['records'] = validate_records(root)
        except (ValueError, OSError, RuntimeError, KeyError, TypeError) as error:
            manifest['records'] = {'status': 'fail', 'error': str(error)}
            raise
        manifest['stages'].append({'name': 'records', 'status': 'pass',
            'operation': 'validate existing graph and both RH audits without updating hashes'})
        run_checks(root, out, manifest)
        print('Regenerating triple normalization and named errors...', flush=True)
        report = generate(root)
        (out/'triple-normalization.json').write_text(json_text(report), encoding='utf-8')
        (out/'triple-normalization.md').write_text(markdown(report), encoding='utf-8')
        manifest['stages'].append({'name': 'normalization', 'status': 'pass',
            'operation': 'exact boundary moments, sector incidence, partition sum and error scaling'})
        if not checks_only:
            build_pdf(root, out, manifest, tools)
        final_state = source_state(root, out, manifest, '-final')
        manifest['source']['final_state'] = final_state
        if final_state != {k: manifest['source'][k] for k in final_state}:
            raise RuntimeError('Git revision or working-tree state changed during reproduction')
        if input_hashes(root) != manifest['inputs']:
            raise RuntimeError('source inputs changed during reproduction')
        manifest['status'] = 'partial' if checks_only else 'pass'
    except (OSError, ValueError, RuntimeError, KeyError, TypeError) as error:
        manifest.update(status='fail', error=str(error))
    finally:
        manifest['finished_utc'] = datetime.now(timezone.utc).isoformat()
        manifest['outputs'] = {str(p.relative_to(out)): sha256(p) for p in sorted(out.rglob('*'))
                               if p.is_file() and p != out/'manifest.json'}
        (out/'manifest.json').write_text(json.dumps(manifest, indent=2, sort_keys=True)+'\n', encoding='utf-8')
    print(f"Triple reproduction {manifest['status']}: {out}", flush=True)
    if manifest['status'] == 'fail':
        print(manifest['error'], file=sys.stderr)
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--checks-only', action='store_true', help='explicit partial run without TeX')
    parser.add_argument('--require-clean', action='store_true', help='reject a dirty Git tree')
    parser.add_argument('--output-dir', type=Path, help='new/empty destination; in repo use artifacts/reproduction/')
    args = parser.parse_args()
    try:
        out = prepare_output(ROOT, args.output_dir)
    except (OSError, ValueError) as error:
        parser.error(str(error))
    return int(reproduce(ROOT, out, args.checks_only, args.require_clean)['status'] == 'fail')


if __name__ == '__main__':
    sys.exit(main())
